### ISSUE TITLE
Req.user only available on GET requests

### ISSUE THREAD

**Issue by ruben1** [jaredhanson/passport#381] opened 2015-07-16 17:16 UTC
So I have this weird bug where If the route is a get request i have access to req.user inside my router handler but if the route is patch, put or post, it's undefined. 
I just have this middleware function that I attach to the routes I want to protect. When the route is get, it works perfectly, but not for other methods.
 
    var isAuthUser = function(req, res, next) {
      var userID = parseInt(req.params.userID);

      if(req.user.userID === userID) {
        next();
      } else {
        res.status(401).end();
      } 
    }

Is this a known problem?

**Comment by jaredhanson** [comment] 2015-07-16 17:26
No.  I suspect this is a problem with your application setup somehow.  Closing, as I am unable to reproduce this.  If you can specifically identify this as a problem with this project, reopen the issue.

**Closed** 2015-07-16 18:39 UTC
