### ISSUE TITLE
Passport strategies

### ISSUE THREAD

**Issue by StanislavBerezin** [jaredhanson/passport#637] opened 2017-12-22 16:43 UTC
Hey, by some reason on your website there are only 5 strategies, which makes it really inconvenient to search through them. Is it something that can be fixed or this is just the way its gonna be?

**Comment by FNGR2911** [comment] 2018-01-16 08:00
Same here. Wondering if thats the intention?

**Comment by StanislavBerezin** [comment] 2018-01-16 08:07
I think the guy who has created passport decided to ditch this project :( quite said

**Comment by jaredhanson** [comment] 2018-01-16 17:45
The strategy search is slow, because it's paging in the data one at a time, and it needs to be parallelized.  If anyone is interested in finishing this work, the code is here: https://github.com/passport/www.passportjs.org/blob/master/web/script/search/packages/remote/api-v1/all.js#L27

If not, then I will work on it as I have time.  I have not ditched this project.  As with all websites, it needs ongoing maintenance.  Meanwhile, the actual passport library is functioning just fine and does not need changes.  Thanks!

**Comment by jaredhanson** [comment] 2018-01-16 17:46
Duplicate of https://github.com/passport/www.passportjs.org/issues/65.

**Closed by jaredhanson** 2018-01-16 17:46 UTC
