### ISSUE TITLE
Redirect does not call pass

### ISSUE THREAD

**Issue by nolaexe** [jaredhanson/passport#753] opened 2020-01-07 17:21 UTC
Hi,
I'm using passport with openid-client. Looks like there's a bug in the implantation of the `redirect()` method. The `redirect()` method does not call `pass()` at the end of redirect.
Not calling `pass()` means never calling the callback, thus never calling the next middleware functions.
I opened a bug for openid-client about the bug: https://github.com/panva/node-openid-client/issues/217
The response for my issue was that it should be fixed in passport, and I agree.

### Expected behavior

Calling `strategy.redirect()` should call `strategy.pass()` before returning, allowing the following middleware to run.

### Actual behavior

Calling `strategy.redirect()` does not call `strategy.pass()`, thus never calling the next middleware.

### Steps to reproduce

1. Initialize a new passport instance
2. Create and configure an OpenId strategy using openid-client
3. Call passport.authenticate, then call the returned function with req, res and next that calls console.log('test')
4. This console.log will never be called

### Environment

* Operating System: Windows 10
* Node version: 12.9.1
* passport version: 0.4.0

**Comment by jaredhanson** [comment] 2020-01-07 18:03
> Not calling pass() means never calling the callback, thus never calling the next middleware functions.

What callback are you referring to?  If it's the strategy `verify` callback, that is only called when there is a user who has been authenticated.  Because that only happens _after_ a return from the redirect, there is no need call next when redirecting.

No other strategies (OAuth 1, OAuth 2, etc) call `pass` after redirecting to the IdP.  It is unclear exactly what code you are trying to execute after redirecting, so if you could provide details, that would be helpful.

**Comment by nolaexe** [comment] 2020-01-08 11:20
Thanks for the reply.
I'm not referring the verify callback. 
I'm referring the callback that is being passed to the `authenticate()` method as the last argument (passport module authenticate.js: 70: `function authenticate(passport, name, options, callback)`).

My problem is that I'm using `promisify` to run `passport.authenticate` asynchronously.
Then I await for the promise to return, but it never returns because the callback that `promisify` sets is never called.
I have some logic to run after the await, but this code is never reached.

**Comment by jaredhanson** [comment] 2020-01-09 17:18
`passport.authenticate` returns a middleware function.  Such middleware is meant to exist in a chain, where each middleware in the chain either:
1. Calls next to proceed processing
2. Doesn't call next, halting the middleware chain because request processing is complete.

This is in contrast to Promise chains, which are all expected to resolve or reject.

In the case of Passport, when the request is redirected, that is the final action, and the chain is halted.  Only during succesful authentication (on the redirect, in OIDC) is next called, invoking callbacks and further middleware.

Wrapping passport in `promisify` is an antipattern, and the cause of your issue.

Closing, since this is working as designed.

**Closed by jaredhanson** 2020-01-09 17:18 UTC
