### ISSUE TITLE
since 0.6 req#logout requires a callback function

### ISSUE THREAD

**Issue by simllll** [jaredhanson/passport#909] opened 2022-05-31 20:47 UTC
since the latest version logout seems to require a callback function, 
but @types/passport is saying there isn't even a parameter
![image](https://user-images.githubusercontent.com/5757263/171281500-158f1435-762c-42dc-8dcb-63ad8776c0fc.png)

I do not explicity register any session manager, .. looking at the code it seems this is only required if there is a session manager.. or is this somehow the default now?
see https://github.com/jaredhanson/passport/blob/42630cbd1ffd44d146ff96f0a4be6f3c12f81d75/lib/http/request.js

### Expected behavior
no callback required

### Actual behavior
a callback is "suddenly" required

**Comment by jaredhanson** [comment] 2022-05-31 21:10
Duplicate of #902.

**Comment by jaredhanson** [comment] 2022-05-31 21:12
This change is intentional, as described in the release [announcement](https://medium.com/passportjs/fixing-session-fixation-b2b68619c51d). It is necessary in order to improve the security of how sessions are managed during logout. Upgrading to 0.6.0 will require applications to pass a callback to req#logout. I'm still working on updating the docs and examples.

I don't maintain the TypeScript types, so those may be out-of-date of the most recent changes.

**Closed by jaredhanson** 2022-05-31 21:12 UTC
Labels: duplicate, wontfix
